services:
  ##################################################################################################
  # nginx configuration
  ##################################################################################################
  ports:
    - 80
    - 443 ssl
  paths:

  ##################################################################################################
  # backend configuration
  ##################################################################################################
  - path: '^~ /admin/'
    backend:
      serviceName: backend
      servicePath: /admin/
      servicePort: 8000

  - path: '^~ /static/'
    backend:
      serviceName: backend
      servicePath: /static/
      servicePort: 8000

  - path: '^~ /api/'
    backend:
      serviceName: backend
      servicePath: /api/
      servicePort: 8000


  ##################################################################################################
  # frontend configuration
  ##################################################################################################
  - path: /
    backend:
      serviceName: frontend
      servicePort: 4200
